
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Jun 23 10:12:57 CST 2014
//----------------------------------------------------

package parsers.frc.ts;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 45;
  public static final int BOOL = 21;
  public static final int ASK = 64;
  public static final int NEWLINE = 79;
  public static final int GEQL = 62;
  public static final int TEXTO = 25;
  public static final int TIMESEQUALS = 55;
  public static final int RPAREN = 37;
  public static final int POW = 52;
  public static final int LPAREN = 36;
  public static final int LEQL = 63;
  public static final int FALSE = 67;
  public static final int EQL = 40;
  public static final int NOT = 59;
  public static final int ARRAY = 7;
  public static final int DEC = 78;
  public static final int FLOAT = 20;
  public static final int NUM = 77;
  public static final int MINUSEQUALS = 54;
  public static final int LIENZO = 30;
  public static final int CLASS = 71;
  public static final int COMA = 47;
  public static final int TRUE = 66;
  public static final int SHARP = 32;
  public static final int PLUS = 41;
  public static final int WHILE = 17;
  public static final int EXTENDS = 72;
  public static final int CHAR = 23;
  public static final int DIVEQUALS = 56;
  public static final int SWITCH = 8;
  public static final int IMPRIMIR = 31;
  public static final int DO = 16;
  public static final int FOR = 15;
  public static final int GREATER = 34;
  public static final int VOID = 6;
  public static final int DIV = 44;
  public static final int PUBLIC = 4;
  public static final int OVALO = 28;
  public static final int RETURN = 70;
  public static final int ELSE = 13;
  public static final int LINEA = 24;
  public static final int BREAK = 10;
  public static final int DOT = 35;
  public static final int INT = 19;
  public static final int NULL = 68;
  public static final int EOF = 0;
  public static final int THIS = 69;
  public static final int DEFAULT = 11;
  public static final int POLIGONO = 29;
  public static final int IMPORT = 3;
  public static final int MINUS = 42;
  public static final int NOTEQL = 61;
  public static final int RHOOK = 49;
  public static final int OR = 58;
  public static final int error = 1;
  public static final int PLUSEQUALS = 53;
  public static final int CHR = 76;
  public static final int CONTINUE = 14;
  public static final int IF = 12;
  public static final int ID = 74;
  public static final int MINUSMINUS = 51;
  public static final int COLON = 65;
  public static final int FILE = 2;
  public static final int RBRACKET = 39;
  public static final int REF = 46;
  public static final int LHOOK = 48;
  public static final int RECTANGULO = 27;
  public static final int CASE = 9;
  public static final int PLUSPLUS = 50;
  public static final int NEW = 18;
  public static final int STRING = 22;
  public static final int LESS = 33;
  public static final int AND = 57;
  public static final int PRIVATE = 5;
  public static final int STATIC = 73;
  public static final int UMINUS = 43;
  public static final int LBRACKET = 38;
  public static final int EQUALS = 60;
  public static final int CAD = 75;
  public static final int ARC0 = 26;
}

