
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Jun 14 05:39:32 CST 2014
//----------------------------------------------------

package parsers.pj;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RUTA = 6;
  public static final int ARCHIVO = 8;
  public static final int OPEN = 2;
  public static final int PROYECTO = 4;
  public static final int EOF = 0;
  public static final int EQL = 11;
  public static final int ARCHIVOS = 7;
  public static final int CLOSE = 3;
  public static final int error = 1;
  public static final int PRECLOSE = 10;
  public static final int NOMBRE = 5;
  public static final int CAD = 12;
  public static final int PRINCIPAL = 9;
}

