
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Jul 05 06:28:51 CST 2014
//----------------------------------------------------

package jbc.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LHOOK = 21;
  public static final int POW = 23;
  public static final int INT_STRING = 38;
  public static final int LBRACKET = 14;
  public static final int EQUALS = 24;
  public static final int IMPRIMIR = 9;
  public static final int LPAREN = 12;
  public static final int GREATER = 11;
  public static final int INT_FLOAT = 39;
  public static final int LESS = 10;
  public static final int MINUS = 18;
  public static final int RPAREN = 13;
  public static final int INT_CHAR = 41;
  public static final int LIENZO = 8;
  public static final int CALL = 33;
  public static final int DIV = 19;
  public static final int RHOOK = 22;
  public static final int CHAR_STRING = 45;
  public static final int POLIGONO = 7;
  public static final int NUM = 47;
  public static final int PLUS = 17;
  public static final int IF = 35;
  public static final int ID = 46;
  public static final int EOF = 0;
  public static final int METHOD = 32;
  public static final int RBRACKET = 15;
  public static final int HEAP = 31;
  public static final int OVALO = 6;
  public static final int error = 1;
  public static final int SEMI_COLON = 29;
  public static final int STACK = 30;
  public static final int STRCAT = 37;
  public static final int FLOAT_STRING = 42;
  public static final int TIMES = 20;
  public static final int COLON = 28;
  public static final int FLOAT_INT = 40;
  public static final int CHAR_INT = 44;
  public static final int RECTANGULO = 5;
  public static final int GOTO = 34;
  public static final int EQL = 16;
  public static final int THEN = 36;
  public static final int ARC0 = 4;
  public static final int DEC = 48;
  public static final int NOTEQL = 25;
  public static final int TEXTO = 3;
  public static final int GEQL = 26;
  public static final int BOOL_STRING = 43;
  public static final int LINEA = 2;
  public static final int LEQL = 27;
}

