
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Jun 30 15:42:58 CST 2013
//----------------------------------------------------

package gui.syntax.highlighter;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int COMENT = 1;
  public static final int SIGNO = 2;
  public static final int OPERADOR = 3;
  public static final int VALUE = 4;
  public static final int CADENA = 5;
  public static final int RESERVADA = 6;
  public static final int TIPO = 7;
  public static final int ID = 8;
  public static final int E_BLANCO = 9;
  public static final int ERROR = 10;
  public static final int FILE = 11;
  public static final int EOF =0;
}

